# Generated by Django 3.1.7 on 2021-03-23 12:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VegOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, help_text='\n            Anything to say about your pledge? This will be publicly visible.\n            ', max_length=225, null=True, verbose_name='comments')),
                ('pledge_start', models.DateField(default=django.utils.timezone.now, verbose_name='pledge start')),
                ('current_meals', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=12)], verbose_name='current meals')),
                ('veggie_meals', models.FloatField(choices=[(2.5, '1 to 5'), (3.0, '6 to 10'), (3.5, '10+')], default=2.5, verbose_name='veggie meals')),
                ('version', models.FloatField(default=1.0, verbose_name='calculation version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'veg out pledge',
                'verbose_name_plural': 'veg out pledges',
            },
        ),
        migrations.CreateModel(
            name='CleanBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, help_text='\n            Anything to say about your pledge? This will be publicly visible.\n            ', max_length=225, null=True, verbose_name='comments')),
                ('pledge_start', models.DateField(default=django.utils.timezone.now, verbose_name='pledge start')),
                ('number_of_people', models.PositiveIntegerField(help_text='\n            The number of people currently living in your house.\n            ', validators=[django.core.validators.MaxValueValidator(limit_value=12)], verbose_name='number of people')),
                ('energy_supplier', models.FloatField(choices=[(0.5, 'Bog Standard'), (0.0, 'Great Green Tariff')], help_text='\n            Your current energy supplier.\n            ', verbose_name='energy supplier')),
                ('heating_source', models.FloatField(choices=[(5.0, 'Gas or Oil'), (3.0, 'Electicity')], help_text='\n            Your current heating source.\n            ', verbose_name='heating source')),
                ('version', models.FloatField(default=1.0, verbose_name='calculation version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clean bill pledge',
                'verbose_name_plural': 'clean bill pledges',
            },
        ),
    ]
