# Generated by Django 3.1.7 on 2021-03-23 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanbill',
            name='number_of_people',
            field=models.PositiveIntegerField(help_text='\n            The number of people currently living in your house.\n            ', validators=[django.core.validators.MaxValueValidator(limit_value=42)], verbose_name='number of people'),
        ),
        migrations.AlterField(
            model_name='vegout',
            name='current_meals',
            field=models.PositiveIntegerField(help_text='\n            The current amount of meaty meals you have each week.\n            ', validators=[django.core.validators.MaxValueValidator(limit_value=12)], verbose_name='current meals'),
        ),
        migrations.AlterField(
            model_name='vegout',
            name='veggie_meals',
            field=models.FloatField(choices=[(2.5, '1 to 5'), (3.0, '6 to 10'), (3.5, '10+')], default=2.5, help_text='\n            The amount of meals you wish to go veggie for.\n            ', verbose_name='veggie meals'),
        ),
    ]
