# Generated by Django 3.1.7 on 2021-03-23 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pledges', '0002_auto_20210323_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanbill',
            name='number_of_people',
            field=models.PositiveIntegerField(help_text='\n            The number of people currently living in your house.\n            ', validators=[django.core.validators.MaxValueValidator(limit_value=12)], verbose_name='number of people'),
        ),
        migrations.AlterField(
            model_name='vegout',
            name='current_meals',
            field=models.PositiveIntegerField(help_text='\n            The current amount of meaty meals you have each week.\n            ', validators=[django.core.validators.MaxValueValidator(limit_value=42)], verbose_name='current meals'),
        ),
    ]
